### PR TITLE
User service review

### PR DESCRIPTION
**Pull request by marcinwozniak0**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/NMarcin/MessengerOnFileForLinux/pull/1%23issuecomment-370258460%22%2C%20%22https%3A//github.com/NMarcin/MessengerOnFileForLinux/pull/1%23issuecomment-370258521%22%2C%20%22https%3A//github.com/NMarcin/MessengerOnFileForLinux/pull/1%23issuecomment-370258678%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/NMarcin/MessengerOnFileForLinux/pull/1%23issuecomment-370258460%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%200%20of%208%20files%20reviewed%20at%20latest%20revision%2C%202%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%2A%5BMessengerOnFileForLinux/user_service/src/RegisterUser.cpp%2C%20line%2021%20at%20r1%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%23-L6mZqzevvG5RPb4begf%3A-L6mZqzf_Hq4NkNds2mD%3Ab-mjh29l%29%20%28%5Braw%20file%5D%28https%3A//github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.cpp%23L21%29%29%3A%2A%5Cn%3E%20%60%60%60cpp%5Cn%3E%20%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%5Cn%3E%20%20%20%20%20%7D%5Cn%3E%20%20%20%20%20return%20false%3B%5Cn%3E%20%60%60%60%5Cn%5CnTESTOWY%20KOMENTRARZ%20%40nmarcin%20%5Cn%5Cn---%5Cn%5Cn%2A%5BMessengerOnFileForLinux/user_service/src/RegisterUser.hpp%2C%20line%204%20at%20r1%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%23-L6m_CsLuN9l2JD9Jb5p%3A-L6m_CsLuN9l2JD9Jb5q%3Abfg2end%29%20%28%5Braw%20file%5D%28https%3A//github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.hpp%23L4%29%29%3A%2A%5Cn%3E%20%60%60%60cpp%5Cn%3E%20%23include%20%3Cstring%3E%5Cn%3E%20%23include%20%5C%22User.hpp%5C%22%5Cn%3E%20%60%60%60%5Cn%5CnKOLEJNY%20TESTOWY%20KOMENTARZ%20%40nmarcin%20%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222018-03-04T19%3A55%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/36385922%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/marcinwozniak0%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%200%20of%208%20files%20reviewed%20at%20latest%20revision%2C%202%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%2A%5BMessengerOnFileForLinux/user_service/src/RegisterUser.cpp%2C%20line%2021%20at%20r1%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%23-L6mZqzevvG5RPb4begf%3A-L6m_VYX4zHvSpy6-s3F%3Ab-896fix%29%20%28%5Braw%20file%5D%28https%3A//github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.cpp%23L21%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20marcinwozniak0%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%3Cblockquote%3E%5Cn%5CnTESTOWY%20KOMENTRARZ%20%40nmarcin%20%5Cn%3C/blockquote%3E%3C/details%3E%5Cn%5CnDone.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222018-03-04T19%3A56%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/36385922%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/marcinwozniak0%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%200%20of%208%20files%20reviewed%20at%20latest%20revision%2C%202%20unresolved%20discussions.%5Cn%5Cn---%5Cn%5Cn%2A%5BMessengerOnFileForLinux/user_service/src/RegisterUser.hpp%2C%20line%204%20at%20r1%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%23-L6m_CsLuN9l2JD9Jb5p%3A-L6m_vAgC0UGxtYVdNy8%3Ab-896fix%29%20%28%5Braw%20file%5D%28https%3A//github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.hpp%23L4%29%29%3A%2A%5Cn%3Cdetails%3E%3Csummary%3E%3Ci%3EPreviously%2C%20marcinwozniak0%20wrote%5Cu2026%3C/i%3E%3C/summary%3E%3Cblockquote%3E%5Cn%5CnKOLEJNY%20TESTOWY%20KOMENTARZ%20%40nmarcin%20%5Cn%3C/blockquote%3E%3C/details%3E%5Cn%5CnDone.%5Cn%5Cn---%5Cn%5Cn%5Cn%2AComments%20from%20%5BReviewable%5D%28https%3A//reviewable.io%3A443/reviews/nmarcin/messengeronfileforlinux/1%29%2A%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222018-03-04T19%3A58%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/36385922%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/marcinwozniak0%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/NMarcin/MessengerOnFileForLinux/pull/1#issuecomment-370258460'>General Comment</a></b>
- <a href='https://github.com/marcinwozniak0'></a> Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.
---
*[MessengerOnFileForLinux/user_service/src/RegisterUser.cpp, line 21 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6mZqzevvG5RPb4begf:-L6mZqzf_Hq4NkNds2mD:b-mjh29l) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.cpp#L21)):*
> ```cpp
>             return true;
>     }
>     return false;
> ```
TESTOWY KOMENTRARZ @nmarcin
---
*[MessengerOnFileForLinux/user_service/src/RegisterUser.hpp, line 4 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6m_CsLuN9l2JD9Jb5p:-L6m_CsLuN9l2JD9Jb5q:bfg2end) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.hpp#L4)):*
> ```cpp
> #include <string>
> #include "User.hpp"
> ```
KOLEJNY TESTOWY KOMENTARZ @nmarcin
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1)*

- <a href='https://github.com/marcinwozniak0'></a> Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.
---
*[MessengerOnFileForLinux/user_service/src/RegisterUser.cpp, line 21 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6mZqzevvG5RPb4begf:-L6m_VYX4zHvSpy6-s3F:b-896fix) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.cpp#L21)):*
<details><summary><i>Previously, marcinwozniak0 wrote…</i></summary><blockquote>
TESTOWY KOMENTRARZ @nmarcin
</blockquote></details>
Done.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1)*

- <a href='https://github.com/marcinwozniak0'></a> Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.
---
*[MessengerOnFileForLinux/user_service/src/RegisterUser.hpp, line 4 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6m_CsLuN9l2JD9Jb5p:-L6m_vAgC0UGxtYVdNy8:b-896fix) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.hpp#L4)):*
<details><summary><i>Previously, marcinwozniak0 wrote…</i></summary><blockquote>
KOLEJNY TESTOWY KOMENTARZ @nmarcin
</blockquote></details>
Done.
---
*Comments from [Reviewable](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1)*

<a href='https://www.codereviewhub.com/NMarcin/MessengerOnFileForLinux/pull/1?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/NMarcin/MessengerOnFileForLinux/pull/1?approve=1'></a>&nbsp;<a href='https://github.com/NMarcin/MessengerOnFileForLinux/pull/1'></a>
<a href='#crh-end'></a>

---
This change is [Reviewable](https://reviewable.io/reviews/nmarcin/messengeronfileforlinux/1)

***
***
***

### CODE REVIEW

**Comment by NMarcin** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/NMarcin/MessengerOnFileForLinux/pull/1'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by marcinwozniak0** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[MessengerOnFileForLinux/user_service/src/RegisterUser.cpp, line 21 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6mZqzevvG5RPb4begf:-L6mZqzf_Hq4NkNds2mD:b-mjh29l) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.cpp#L21)):*
> ```cpp
>             return true;
>     }
>     return false;
> ```

TESTOWY KOMENTRARZ @nmarcin 

---

*[MessengerOnFileForLinux/user_service/src/RegisterUser.hpp, line 4 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6m_CsLuN9l2JD9Jb5p:-L6m_CsLuN9l2JD9Jb5q:bfg2end) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.hpp#L4)):*
> ```cpp
> #include <string>
> #include "User.hpp"
> ```

KOLEJNY TESTOWY KOMENTARZ @nmarcin 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1)*

**Comment by marcinwozniak0** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[MessengerOnFileForLinux/user_service/src/RegisterUser.cpp, line 21 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6mZqzevvG5RPb4begf:-L6m_VYX4zHvSpy6-s3F:b-896fix) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.cpp#L21)):*
<details><summary><i>Previously, marcinwozniak0 wrote…</i></summary><blockquote>

TESTOWY KOMENTRARZ @nmarcin 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1)*

**Comment by marcinwozniak0** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[MessengerOnFileForLinux/user_service/src/RegisterUser.hpp, line 4 at r1](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1#-L6m_CsLuN9l2JD9Jb5p:-L6m_vAgC0UGxtYVdNy8:b-896fix) ([raw file](https://github.com/nmarcin/messengeronfileforlinux/blob/edf7a9181f3690951f3e72eeae1f9af31a5f0b61/MessengerOnFileForLinux/user_service/src/RegisterUser.hpp#L4)):*
<details><summary><i>Previously, marcinwozniak0 wrote…</i></summary><blockquote>

KOLEJNY TESTOWY KOMENTARZ @nmarcin 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nmarcin/messengeronfileforlinux/1)*

**Pull request closed without merging**
